version: 2.1
executors:
  exectr:
    docker:
      - image: mustihanni/dockerfilerepositoryforcpp:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup gtest child repo
          command: |
            cd third_party
            git submodule init
            git submodule update 
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir -p build && cd build
            cmake .. -DTESTS_REQUIRED=ON
            make
      - persist_to_workspace:
          root: .
          paths: build

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build/tests/unit_tests
            ./simpleproject_test --gtest_output=XML
      - store_test_results:
          path: build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
